*open_model rolls\posco_wr_f4_f7_r1_base.mud
*remove_surfaces 
12 16 #
*remove_curves
35 36 #
*origin
  0.0000000000  3.400000000000e+002  0.000000000000
*set_curve_type arc_ppp
*add_curves
  1.040000000000e+003 0.000000000000e+000 0.000000000000e+000
 -1.040000000000e+003 0.000000000000e+000 0.000000000000e+000
0 wr_crown 0
*sub_divisions
2
1
1
*subdivide_curves_real
 65
# | End of List
*move_reset
*set_move_translation y dia_chg/2.0
*move_curves 66 67 #
*flip_curves
66 67 #
*set_surface_type ruled
*add_surfaces
57 67 
58 66 
*sweep_all
*set_convert_uvdiv u 15
*set_convert_uvdiv v 2
*convert_surfaces
 25
# | End of List
*set_convert_uvdiv u 15
*set_convert_uvdiv v 1
*convert_surfaces
 10 11
# | End of List
*set_convert_uvdiv u 15
*set_convert_uvdiv v 3
*convert_surfaces
 9
# | End of List
*set_convert_uvdiv u 5
*set_convert_uvdiv v 1
*convert_surfaces
 7 8
# | End of List
*set_convert_uvdiv v 3
*convert_surfaces
 6
# | End of List
*set_convert_uvdiv u 1
*set_convert_uvdiv v 1
*convert_surfaces
 5
# | End of List
*set_convert_uvdiv v 3
*convert_surfaces
 2 3 4 6
# | End of List
*set_convert_uvdiv u 3
*convert_surfaces
1 
# | End of List
*sweep_all
*system_reset
*move_reset
*set_move_rotation y 90
*move_model
*select_method_box
*select_edges
-100 100
-5000 5000
-0.1 0.1
@set($convert_entities,edges)
*edge_lines
all_selected
*select_elements
-100 100
-5000 5000
-0.1 0.1
*set_expand_translation z -50
*expand_elements
all_selected
*select_clear
*select_method_single
| *save_as_model wr_f4_f7.mud yes
