| Created by Marc Mentat 2014.2.0 (64bit)
*prog_option compatibility:prog_version:ment2014
*prog_analysis_class structural
*prog_use_current_job on
*set_default_length_unit millimeter
*set_model_length_unit millimeter
|
|  ADD Global Remeshing Option 
|
*new_adapg *adapg_type mesh_file_3d
*adapg_name
plate_remesh
*adapg_rmsh_body
01_Plate
*adapg_option immediate_crit:on
*edit_loadcase lcase0
*add_loadcase_adapgs plate_remesh